[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_FLAGS = "--version"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https:; connect-src 'self' https: wss: bsky.social *.bsky.social *.stripe.com *.netlify.com dev.dogpoopers.com *.rss.com *.dogpoopers.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.youtube.com *.twitter.com *.disqus.com *.rss.com *.google.com *.googleapis.com *.gstatic.com *.stripe.com *.netlify.com; style-src 'self' 'unsafe-inline' https: *.googleapis.com; img-src 'self' data: https: http: blob: *.googleapis.com *.gstatic.com *.google.com *.twitter.com *.twimg.com *.rss.com *.youtube.com; media-src 'self'; frame-src *.rss.com *; font-src 'self' data: *.gstatic.com *.googleapis.com; frame-ancestors *;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[redirects]]
  from = "/pirate/*"
  to = "/pirate/:splat"
  status = 200